//
// Created by Devisha Dhanuka on 27/06/23.
//

#ifndef RUBIKSCUBESOLVER_GENERICRUBIKSCUBE_H
#define RUBIKSCUBESOLVER_GENERICRUBIKSCUBE_H


class GenericRubiksCube {

};


#endif //RUBIKSCUBESOLVER_GENERICRUBIKSCUBE_H
